spring:
  datasource:
    url: jdbc:mysql://localhost:3306/deliveritdb
    username: root
    password: password
  JPA:
    hibernate:
      ddl-auto: update
      properties:
        hibernate:
          format_sql: true



